spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tacoInAction
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  thymeleaf:
    cache: false
  data:
    rest:
      base-path: /data-api

amex:
  card1: 374245455400126
  card2: 378282246310005